version: '3.8'

services:
    # Nginx Service
    nginx:
        image: nginx:latest
        container_name: testhub-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php
        networks:
            - testhub-network

    # MySQL Service
    mysql:
        image: mysql:8.0
        container_name: testhub-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: testhub
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - testhub-network

    # PHP Service
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: testhub-php
        volumes:
            - ./:/var/www
        working_dir: /var/www
        depends_on:
            - mysql
        command: >
            bash -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
                    chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
                    php-fpm"
        networks:
            - testhub-network

networks:
    testhub-network:
        driver: bridge

volumes:
    mysql-data:
